### DISCUSSION TITLE
Battery Entity Card mod

### DISCUSSION THREAD

**Discussion by Daibutt** [StealthChesnut/HA-FoxESS-Modbus#19] [Show and tell]
I find the gauge card OK for battery SoC level, but wanted to know whether it was charging as well, in a small/discrete card and came up with this;
![image](https://user-images.githubusercontent.com/69276073/169226093-749a4094-8049-4f99-9d78-941bcfa16ce1.png)

I used the Battery State Card HACS frontend integration;
![image](https://user-images.githubusercontent.com/69276073/169226329-8ab44b9c-b31a-445f-b173-08377d88ff14.png)

Added a template sensor to give a charging 'On' sensor if charge rate was > 0.1 kW
```
    battery_charging:
      friendly_name: "Battery charging"
      value_template: >
          {% if (states('sensor.battery_charge') | float > 0.1 ) %}
          {{ "On" }}
          {% else %}
          {{ "Off" }}
          {% endif %}

```

And then added this as a manual Lovelace card;

```
type: custom:battery-state-card
title: null
sort_by_level: asc
color_thresholds:
  - value: 10
    color: '#00b3ff'
  - value: 20
    color: '#ff0000'
  - value: 25
    color: '#ff4000'
  - value: 50
    color: '#ff8000'
  - value: 60
    color: '#ffc400'
  - value: 70
    color: '#d0ff00'
  - value: 80
    color: '#99ff00'
  - value: 90
    color: '#6aff00'
  - value: 100
    color: '#1eff00'
unit: '%'
entities:
  - entity: sensor.battery_soc
    name: Solar Battery
    charging_state:
      entity_id: sensor.battery_charging
      state: 'On'
    tap_action: more-info
card_mod:
  style: |
    ha-card {
      font-size: 18px;
      --mdc-icon-size: 36px;
    }
```

You can alter the colours and the thresholds for each colour in the top part.
