### DISCUSSION TITLE
Example Energy Dashboard

### DISCUSSION THREAD

**Discussion by williamjeccles** [StealthChesnut/HA-FoxESS-Modbus#4] [Show and tell]
A quick energy dashboard that should just drop in and work if you've not changed any sensor names

![image](https://user-images.githubusercontent.com/6324545/166508208-f8fb247c-0e56-4c6b-b4ed-f7e75305227f.png)

```

views:
  - title: Home
    cards:
      - type: gauge
        entity: sensor.battery_soc
        severity:
          green: 25
          yellow: 11
          red: 0
        name: Remaining Battery
        needle: true
      - type: energy-solar-graph
      - type: gauge
        entity: sensor.pv_total_power
        name: Solar
        min: 1
        max: 6
        needle: true
        severity:
          green: 1.5
          yellow: 1.3
          red: 0
      - type: gauge
        entity: sensor.grid_consumption
        severity:
          green: 0
          yellow: 0.5
          red: 1
        min: 0.1
        max: 3
        needle: true
      - type: gauge
        entity: sensor.load_power
        name: Inverter Load
        needle: true
        severity:
          green: 0
          yellow: 4.9
          red: 5
        min: 1
        max: 5.2
      - type: vertical-stack
        cards:
          - type: entity
            entity: sensor.pv_total_daily
            name: Solar Generation (Today)
            icon: mdi:solar-power
          - type: entity
            entity: sensor.grid_daily
            name: Gird Use (Today)
            icon: mdi:transmission-tower
          - type: entity
            entity: sensor.feedin_daily
            name: Feed In (Today)
      - type: entities
        entities:
          - entity: sensor.battery_charge
            name: Battery Charge Rate
            icon: mdi:battery
          - entity: sensor.battery_discharge
            name: Battery Discharge Rate
            icon: mdi:battery-20
          - entity: sensor.battery_temp
            name: Battery Temperature
            icon: mdi:temperature-celsius
          - entity: sensor.invtemp
            name: Inverter Temperature
            icon: mdi:air-filter
          - entity: sensor.invbatvolt
            name: Battery Voltage
            icon: mdi:battery-charging-100
        state_color: false
      - type: gauge
        entity: sensor.feed_in_power
        min: 1
        max: 5000
        needle: true




```
