### DISCUSSION TITLE
Resolve small negative values for Solar PV just after sunset

### DISCUSSION THREAD

**Discussion by williamjeccles** [StealthChesnut/HA-FoxESS-Modbus#7] [Show and tell]
Due to the way solar panels work, I've noticed just after sunset small blips of negative values on the PV Power Now metric.

Using the new 2022.05 min/max feature i've been able to resolve these issues by blocking sub 0 values.

**Standard Platform Template:**

```

    pv_total_power:
          friendly_name: "PV Power now"
          unit_of_measurement: 'kW'
          device_class: power
          value_template: >
              {{ (states('sensor.pv1_power') | float + states('sensor.pv2_power') | float ) * 1 }}
```

**Modified to filter out negative values:**

```
    pv_total_power:
          friendly_name: "PV Power now"
          unit_of_measurement: 'kW'
          device_class: power
          value_template: >
              {{ [0, ((states('sensor.pv1_power') | float + states('sensor.pv2_power') | float ) * 1)]|max }}

```
